### ISSUE TITLE
`@scalprum/react-core@0.9.1` depends on `@scalprum/core@^0.7.0` incorrectly

### ISSUE THREAD

**Issue by JounQin** [scalprum/scaffolding#143]
It is said:

> `@scalprum/core` updated to version `0.8.1`

https://github.com/scalprum/scaffolding/blob/main/packages/react-core/CHANGELOG.md#091-2024-09-11

But actually, `@scalprum/core` in `package.json` is still `^0.7.0`

https://unpkg.com/browse/@scalprum/react-core@0.9.1/package.json

https://github.com/scalprum/scaffolding/blob/538e2a09125934f8cf4b24cfcb8e84f8e3859406/packages/react-core/package.json#L18

**Comment by Hyperkid123** [comment]
Packages were bumped and a new version was released. Thanks for the report 🙂
